"use client";

import type { ConversationId, MessageId, RequestId, StreamEvent } from "@agent-chat/chat-core";
import { createId, nowIso } from "@agent-chat/utils";

export interface MockStreamController {
  requestId: RequestId;
  messageId: MessageId;
  cancel(reason?: string): void;
}

interface StartMockStreamInput {
  conversationId: ConversationId;
  requestId: RequestId;
  prompt: string;
  onEvent(event: StreamEvent): void;
  onClose(): void;
}

export function startMockAssistantStream(input: StartMockStreamInput): MockStreamController {
  const messageId = createId("msg") as MessageId;
  const toolCallId = createId("tool");
  const timers: Array<ReturnType<typeof window.setTimeout>> = [];
  let closed = false;

  const emit = (event: StreamEvent) => {
    if (!closed) {
      input.onEvent(event);
    }
  };

  const schedule = (delay: number, task: () => void) => {
    timers.push(
      window.setTimeout(() => {
        if (!closed) {
          task();
        }
      }, delay)
    );
  };

  emit({
    type: "message_start",
    conversationId: input.conversationId,
    messageId,
    requestId: input.requestId,
    role: "assistant",
    createdAt: nowIso()
  });

  const response = buildMockResponse(input.prompt);
  const tokens = tokenize(response);

  tokens.forEach((token, index) => {
    schedule(80 + index * 34, () => {
      emit({
        type: "token",
        messageId,
        delta: token,
        updatedAt: nowIso()
      });
    });
  });

  const toolStartDelay = Math.min(520, 100 + tokens.length * 18);
  schedule(toolStartDelay, () => {
    emit({
      type: "tool_call",
      messageId,
      toolCall: {
        id: toolCallId,
        name: "knowledge_search",
        status: "running",
        argumentsText: JSON.stringify({ query: input.prompt.slice(0, 80) }),
        startedAt: nowIso()
      },
      updatedAt: nowIso()
    });
  });

  schedule(toolStartDelay + 520, () => {
    emit({
      type: "tool_result",
      messageId,
      toolCallId,
      result: {
        source: "mock_frontend_stream",
        confidence: 0.92
      },
      updatedAt: nowIso()
    });
  });

  schedule(140 + tokens.length * 34, () => {
    emit({
      type: "message_done",
      messageId,
      finishReason: "stop",
      updatedAt: nowIso()
    });
    close();
  });

  function close() {
    if (closed) {
      return;
    }
    closed = true;
    timers.forEach((timer) => window.clearTimeout(timer));
    input.onClose();
  }

  return {
    requestId: input.requestId,
    messageId,
    cancel(reason = "Request cancelled.") {
      emit({
        type: "message_error",
        messageId,
        error: reason,
        updatedAt: nowIso()
      });
      close();
    }
  };
}

function buildMockResponse(prompt: string): string {
  const normalizedPrompt = prompt.trim();

  return [
    `I received: "${normalizedPrompt}".`,
    "This is a frontend-only streaming response generated by the mock transport.",
    "The state store is appending tokens incrementally, so the assistant message updates in real time.",
    "A simulated tool call is also attached to the message to exercise tool visualization."
  ].join("\n\n");
}

function tokenize(content: string): string[] {
  return content.match(/\S+\s*/g) ?? [content];
}
